spring:
  security:
    user:
      name: user1
      password: password
    oauth2:
      authorizationserver:
        client:
          oidcclient:
            registration:
              client-id: "oidcclient"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/messaging-client-oidc"
                - "http://127.0.0.1:8080/authorized"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true