spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8090/auth
        client:
          stashless:
            token:
              access-token-time-to-live: 3600s
            registration:
              client-id: "stashless"
              client-secret: "${OIDC_CLIENT_SECRET:{bcrypt}$2a$10$NxzZ6oWTBXdWlRer6tpWjeawuX.Ftu198C3AXgWxV9qBxGiVc1e7O}"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
              redirect-uris:
                - http://localhost:4200
              post-logout-redirect-uris:
                - http://localhost:4200
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "offline_access"
            require-authorization-consent: false
            require-proof-key: true