server:
  port: 8090
spring:
  security:
    user:
      name: user1
      password: password
    oauth2:
      authorizationserver:
        client:
          stashless:
            registration:
              client-id: "stashless"
              client-secret: "${OIDC_CLIENT_SECRET:{bcrypt}$2a$10$NxzZ6oWTBXdWlRer6tpWjeawuX.Ftu198C3AXgWxV9qBxGiVc1e7O}"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
                - "none"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
              redirect-uris:
                - ${CORS_FRONTEND_URL:http://localhost:4200}
              post-logout-redirect-uris:
                - ${CORS_FRONTEND_URL:http://localhost:4200}
              scopes:
                - "openid"
                - "profile"
                - "email"
                - "offline_access"
            require-authorization-consent: false
            require-proof-key: true