management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  config:
    import: optional:file:../.env[.properties]
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:h2:mem:stashlessdb}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        check_nullability: true
  messages:
    always-use-message-format: false
  devtools:
    restart:
      enabled: false


springdoc:
  show-actuator: true
  packages-to-scan: me.heyner.stashless.controller
cors:
  allowed-origins:
    - ${CORS_FRONTEND_URL:http://localhost:4200}